### ISSUE TITLE
Add support for input-groups

### ISSUE THREAD

**Issue by adamwathan** [adamwathan/bootforms#10]
Continuation of this discussion: https://github.com/adamwathan/bootforms/pull/8#issuecomment-38410525

**Comment by kevindierkx** [comment]
I've noticed that the text and password input 'objects' all get wrapped in a GroupWrapper object.
Adding the prepend and append Addon methods to this class would be helpful.

Those methods should only allow certain objects to be provided like a button.

```PHP
BootForm::text('Username', 'username')
->appendAddon(BootForm::button('button', 'Button'));
```

I would suggest adding these methods to the wrapper.

**Comment by zxishere** [comment]
if i need two buttons ,how can i make it? 

<div class="col-lg-offset-2 col-lg-10">
<button class="btn btn-default" type="button">Click Me</button>
<button class="btn btn-default" type="button">Click Me</button>
</div>

**Comment by JerseyMilker** [comment]
Yes please. I like using input-groups for my icons.
![input-group](http://puu.sh/hkGjF/465082cd43.png)

**Comment by canfiax** [comment]
Would be awesome:

![image](https://cloud.githubusercontent.com/assets/3786627/8253047/fd896cba-168b-11e5-9ae6-29ab906353ba.png)

**Comment by ricardovigatti** [comment]
Input groups are not supporting buttons yet ?

**Comment by adamwathan** [comment]
@ricardovigatti I don't think so yet, would happily look at a PR.

**Comment by adamwathan** [comment]
Basic input groups are supported now, no documentation yet unfortunately but tests here: https://github.com/adamwathan/bootforms/blob/master/tests/BasicFormBuilderTest.php#L545-L628

**Comment by ricardovigatti** [comment]
Nice, i'll try to take an extra time here at my job to check the code and maybe add functions to support those input group with buttons. Ty.

**Comment by JesseLeite** [comment]
Slick :+1:

**Comment by andresen007** [comment]
I dont understand, how I make a inputGroup as @JesseLeite is showing, with help from the "tests"-files!

Thanks for the nice job!
