### ISSUE TITLE
addClass for InputGroups

### ISSUE THREAD

**Issue by BlueTeck** [adamwathan/bootforms#104]
Hi,

thanks for your bootforms libary.

It would be nice, if you could add a class to the inputgoupt itself.

```php
BootForm::inputGroup('Farbe', 'background_color')->addClass('colorpicker-component')
```

```html
<div class="form-group colorpicker-component">
   <label class="control-label" for="background_color">Farbe</label>
   <div class="input-group"><span class="input-group-addon">
      <input type="text" name="background_color" value="#408080" id="background_color" class="form-control colorpicker-element">
   </div>
</div>
```

Use case: http://mjolnic.com/bootstrap-colorpicker/ component function

At the moment I have to do:
```html
<div id="cp" class="colorpicker-component">
   {!! BootForm::inputGroup('Farbe', 'background_color')->beforeAddon('<i></i>') !!}
</div>
```

Regards,
Timo

**Comment by ricardovigatti** [comment]
It's working for me:

`{!! BootForm::inputGroup('Farbe', 'background_color')->addClass('colorpicker-component')
    ->beforeAddon('<i></i>') !!}`

**Comment by BlueTeck** [comment]
But not with the same result:

`{!! BootForm::inputGroup('Farbe', 'background_color')->addClass('colorpicker-component')->beforeAddon('<i></i>') !!}`
![image](https://cloud.githubusercontent.com/assets/1961634/16613864/97be2f5e-436e-11e6-969b-a203c1eb630f.png)

```
<div id="cp" class="colorpicker-component">
   {!! BootForm::inputGroup('Farbe', 'background_color')->beforeAddon('<i></i>') !!}
</div>
```
![image](https://cloud.githubusercontent.com/assets/1961634/16613889/b272d30e-436e-11e6-96c8-d73a54265f6f.png)

**Comment by joelcuevas** [comment]
Maybe a little late, but have you tried this?

```
BootForm::inputGroup('Farbe', 'background_color')->addGroupClass('colorpicker-component')
```

**Comment by BlueTeck** [comment]
Perfect, thanks :)
