### ISSUE TITLE
Alter the checkbox HTML structure

### ISSUE THREAD

**Issue by vpratfr** [adamwathan/bootforms#107]
Hi,

I would like to have custom checkboxes, and that is made easy with [flatlogic/awesome-bootstrap-checkbox](https://github.com/flatlogic/awesome-bootstrap-checkbox)

With that package though the markup needs to differ a bit from the standard Bootstrap markup. 

I.e. instead of

```
  <div class="checkbox">
    <label>
      <input type="checkbox"> Check me out
    </label>
  </div>
```

You need to write

```
  <div class="checkbox">
    <input type="checkbox" id="checkbox1">
    <label for="checkbox1">
        Check me out
    </label>
  </div>
```

Which is the easiest way to have your package output that kind of HTML instead of the standard one? 

Is there a way to extend the package maybe by replacing the checkbox class with my own?

**Comment by ricardovigatti** [comment]
+1

**Comment by JesseLeite** [comment]
There isn't a Bootstrap 4 implementation of Bootforms yet.  That said, Bootstrap 4 still suggests we wrap the input with the label.  If you want custom checkbox rendering, you can always extend the package in your app to setup custom checkbox rendering.

**Comment by vpratfr** [comment]
Hi,

The library I mentionned above is not about Bootstrap 4, it works with BS 3 too. And I do not really want you to change your current implementation, that is fine to me.

What I wanted to know is precisely how to extend the package to change the way checkboxes are rendered.

I did not see any docs about it and even after searcing a bit in the source code I did not see how I could register my own component.

**Comment by adamwathan** [comment]
You would have to extend [this class](https://github.com/adamwathan/bootforms/blob/master/src/AdamWathan/BootForms/BasicFormBuilder.php) (and maybe the horizontal one if you are using both) and just override whatever methods you need to to change the markup.

The package doesn't support registering different components or anything out of the box, you'll just need to override whatever methods you discover you need to, like a bunch of stuff around here:

https://github.com/adamwathan/bootforms/blob/master/src/AdamWathan/BootForms/BasicFormBuilder.php#L70-L99
