### ISSUE TITLE
Setting checked value for checkbox

### ISSUE THREAD

**Issue by grafikkaos** [adamwathan/bootforms#116]
How does one set the default value of a checkbox using BootForm?  I am trying the following code but I cant seem to get it to work.  I am using laravel 5.2

``` php
{!! $interestControl = BootForm::checkbox($interest, 'interests[]')->value($interest) !!}
@php
$interestControl->defaultCheckedState($key);
@endphp
```

Any ideas would be great...

**Comment by adamwathan** [comment]
Check the documentation for the underlying form package here:

https://github.com/adamwathan/form#checkboxes-and-radio-buttons
