### ISSUE TITLE
form-group

### ISSUE THREAD

**Issue by hugofabricio** [adamwathan/bootforms#119]
How to remove form-group class or group div of input?

**Comment by adamwathan** [comment]
Can't; this library is designed to make it easy to generate standard Bootstrap form markup. If you need different markup, better to write it by hand or use another library.

Bootforms uses this library under the hood that might be useful:

https://github.com/adamwathan/form

**Comment by JesseLeite** [comment]
@hugofabricio If you chain `removeClass()` after an `group()` like this...
```php
BootForm::text('Wat', 'wat')
    ->group()
    ->removeClass('form-group')
```
It will output...
```html
<div>
    <label class="control-label" for="wat">Wat</label>
    <input type="text" name="wat" id="wat" class="form-control">
</div>
```

Notice the class is removed from parent div.  But as Adam said, there's no way to remove the div itself with Bootforms 👍
