### ISSUE TITLE
Laravel 5.3. Does it support?

### ISSUE THREAD

**Issue by yansusanto** [adamwathan/bootforms#120]
I'm not getting the automatic validation class here

```
{!! BootForm::open() !!}
  {!! BootForm::text('First Name', 'first_name')->placeholder('John Doe') !!}
  {!! BootForm::submit('Submit') !!}
{!! BootForm::close() !!}
```
Am I missing something here?

PS: Oh by the way, thanks for creating this package.

**Comment by joelennon** [comment]
Works fine in Laravel 5.3 for me. Check your validator is working correctly, maybe `{!! var_dump($errors) !!}` will give you an idea of what's going wrong.
