### ISSUE TITLE
Laravel 5.4 Support

### ISSUE THREAD

**Issue by joelcuevas** [adamwathan/bootforms#127]
When using on L5.4 I'm getting the following error on `BootFormsServiceProvider@53`:

```
Call to undefined method Illuminate\Session\Store::getToken() 
```

As the L5.4 upgrade guide states, all calls to `getToken()` should be changed to `token()`. Other than that, everything looks fine. 

@adamwathan do you think that something else should be necessary?

**Comment by grumpysi** [comment]
+1 

Can we get django23's pull request merged?

**Comment by adamwathan** [comment]
Merged.
