### ISSUE TITLE
Select multiple binding

### ISSUE THREAD

**Issue by BreakerYouko** [adamwathan/bootforms#128]
Hi all,
I create a multiple select list in the form, but I want to bind it when the user is updating.
Is there any method to pass the selected array?

**Comment by adamwathan** [comment]
Yep, as long as the object you bind has a property matching the select field's name and has an array of values in that property, it should bind for you:

```php
{!! BootForm::open() !!}

    {!! BootForm::bind($user) !!}}

    {!! BootForm::select('foods', ['fish' => 'Fish', 'chips' => 'Chips', 'candy' => 'Candy'])->multiple() !!}

{!! BootForm::close() !!}
```

```php
$user = new User([
    'foods' => ['fish', 'candy']
]);
```
