### ISSUE TITLE
VusJS custom attributes

### ISSUE THREAD

**Issue by grafikkaos** [adamwathan/bootforms#129]
Is there a way of using VueJS custom attributes with BootForm?

Example of this on a form can be something like v-on:submit="xxxxxxx" or v-model="xxxxxxx"?  

Thanks

**Comment by adamwathan** [comment]
There isn't currently but I'd look at a PR if one was submitted. I would probably never use the package in that way personally, as it's mostly intended for traditional server-side form stuff.

**Comment by grafikkaos** [comment]
No worries... I am quite happy with the way BootForm works at the moment.  Will simply have to revert the the laravel collective for instances where Vue is going to be used.

Thanks 👍

**Comment by JesseLeite** [comment]
@grafikkaos You can always `->attribute('v-on:keyup', 'someCall')`.
