### ISSUE TITLE
Ability to remove label

### ISSUE THREAD

**Issue by sarfraznawaz2005** [adamwathan/bootforms#130]
I think there should be a method to remove label completely instead of having it there with `sr-only` with `hideLabel`. Neither I can use [this](https://github.com/tui2tone/checkbox3) nor [this](https://github.com/flatlogic/awesome-bootstrap-checkbox) without altering core of this package.

I know it's good idea to just hide label with `sr-only` but _let it be responsibility of the user_, package must not enforce it. It's good idea we could do something like this similar to collective/html package:

    {!! BootForm::checkbox('Active', 'is_active', 'is_active', true)->withoutLabel() !!}
    {!! BootForm::label('is_active') !!}

Thanks

**Comment by adamwathan** [comment]
Happy to look at a PR for `withoutLabel` if you want to put one together 👍

**Comment by adamwathan** [comment]
No plans to add this, just write the markup by hand if you'd like different markup than the package generates.
