### ISSUE TITLE
html in label?

### ISSUE THREAD

**Issue by elephantux** [adamwathan/bootforms#136]
In version 0.8.4 I can add html to label and it's work fine:
```{!! BootForm::text('Price <span class="label label-info">discount</span>','discount_price') !!}```

Now (in 0.8.5) it output html with htmlentities as a string.
Any ideas?

**Comment by adamwathan** [comment]
Just tagged a release that fixes this:

https://github.com/adamwathan/bootforms/releases/tag/v0.9.0
