### ISSUE TITLE
Configurable ControllerClasses in horizontal forms

### ISSUE THREAD

**Issue by AlexErmer** [adamwathan/bootforms#35]
In HorizontalFormGroup.php the ControllerClass 'col-lg-' is hardCoded. 

    protected function getControlClass()
    {
        return 'col-lg-' . $this->controlWidth;
    }

Would be nice if this is configurable as well as the width itself. For example I want to set "col-sm-6 col-md-4 col-lg-2" for my labels and different settings for the control in this 3 classes again.

I really like the approach of https://github.com/dwightwatson/bootstrap-form where this can be done via laravel configs.

**Comment by adamwathan** [comment]
Going to try get this in today.

**Comment by troygilbert** [comment]
Did this ever get done? Would really love to just have the option to override the 'lg' at a minimum, even if I don't have the different variations.

**Comment by adamwathan** [comment]
@troygilbert Thanks for reminding me, banged out a quick implementation just now using the syntax I mentioned above. It's a breaking change with no support for the old `openHorizontal(3, 9)` syntax for now, but it would be easy to support both.

Give it a try on this branch if you like and let me know what you think, only had 10 minutes so not a lot of opportunity to think it through too much or test it too thoroughly.

https://github.com/adamwathan/bootforms/tree/aw-custom-breakpoint-columns

**Comment by troygilbert** [comment]
Sorry it took me so long… just updated my admin panels to use this, works perfectly. Thanks!

**Comment by adamwathan** [comment]
Cool! Officially available in v0.5.0 :)
