### ISSUE TITLE
Generate CSRF token automatically

### ISSUE THREAD

**Issue by slovenianGooner** [adamwathan/bootforms#36]
Hi,

with L5 latest update the CSRF middleware is added to the application stack which means it's executed every time. For some reason, your Form Builder is not generating the hidden input for the _token. Any idea why or do we need to call a method?

Thanks!

**Comment by adamwathan** [comment]
Yeah it would be, probably can add an option to have it auto-inserted on form open, would keep it off by default so as to not couple to Laravel, but enable it in the service provider. Good idea.

Keeping this open until I get around to it :)

**Comment by JerseyMilker** [comment]
+1

**Comment by bart** [comment]
+1

**Comment by lapin-b** [comment]
+1 ^^

**Comment by bhasunjaya** [comment]
+1

**Comment by adamwathan** [comment]
Ok ok ok will do it today :)

**Comment by adamwathan** [comment]
Done for 0.6.0, tag is up.
