### ISSUE TITLE
Setting enc type when opening forms

### ISSUE THREAD

**Issue by muzzamilkhan** [adamwathan/bootforms#39]
Hi, 

Is there a way to set enc/type for file uploads? Am i missing something?

**Comment by adamwathan** [comment]
Yes totally can! Should document this :/

```
// <form method="POST" action="" enctype="multipart/form-data">
BootForm::open()->multipart()

// <form method="POST" action="" enctype="custom">
BootForm::open()->encodingType("custom")
```

**Comment by muzzamilkhan** [comment]
Thanks so much!!

**Comment by troygilbert** [comment]
This *really* needs to get put in the documentation. Spent 30 minutes trying to sort this out.

**Comment by adamwathan** [comment]
Added to the form package documentation here: https://github.com/adamwathan/form#opening-a-form

Not sure what the best way to document that BootForms has *all* the same methods as the Form package is. I've tried to make it pretty clear in the documentation, but maybe it's better to straight up duplicate it :/

**Comment by troygilbert** [comment]
Thought I had checked there, sorry. Would be nice if the API was actually itemized. With the examples I'm never quite sure if I'm seeing all the options and/or all their parameters. Thanks for following up!

**Comment by adamwathan** [comment]
You did check, it wasn't there until today ;) I just mean in general. I should probably just expand on the docs more, just don't want it to seem overwhelming for such a conceptually simple package, haha...



—
Adam

**Comment by bcdbuddy** [comment]
It took me 10 minutes to find out how to do it. man this really needs to be documented. Thanks for your job
