### ISSUE TITLE
Uploading multiple files

### ISSUE THREAD

**Issue by irax-xx** [adamwathan/bootforms#42]
I need to upload multiple files in my app. To that with Laravel Forms, one would do 
<pre>
Form::files('files[]',array('multiple'=>true)
</pre>

How can I accomplish this with BootForms?

**Comment by irax-xx** [comment]
Found solution - very elegant.
<pre>
BootForm::file('Images','images')->multiple(1)
</pre>

**Comment by angelodaliwan** [comment]
how to convert the bootform::file to text for save the filename to the database
