### ISSUE TITLE
some questions about form-group

### ISSUE THREAD

**Issue by zxishere** [adamwathan/bootforms#43]
Hi there, i have some questions:

1 can i custon two or more div  width in the same form ?
first <div class="col-sm-5"> and second  <div class="col-sm-8"> like this
2 can i add two or more button in one form-group ?

sorry for my poor english ,Thanks!!!

```html
<form class="form-horizontal" role="form">
  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">Email</label>
    <div class="col-sm-5">
      <input type="email" class="form-control" id="inputEmail3" placeholder="Email">
    </div>
  </div>
  <div class="form-group">
    <label for="inputPassword3" class="col-sm-2 control-label">Password</label>
    <div class="col-sm-8">
      <input type="password" class="form-control" id="inputPassword3" placeholder="Password">
    </div>
  </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="button" class="btn btn-default">button1</button>
      <button type="button"  class="btn btn-default">button2</button>
    </div>
  </div>
</form>
```

**Comment by adamwathan** [comment]
1. Unfortunately it can't handle changing column widths at the moment, and probably won't in the future. This package is just meant for rapid prototyping mostly. Once you need more customized markup, it's better to just do it by hand.

2. There's no real automatic way to do it, but you can use BootForms to create individual buttons manually, like so:

```
BootForm::button('My button', null, 'btn-success');
```
