### ISSUE TITLE
Will there be a support for Laravel 5?

### ISSUE THREAD

**Issue by daverdalas** [adamwathan/bootforms#45]

**Comment by sdebacker** [comment]
It should be great as a replacement of Form class.

**Comment by sdebacker** [comment]
It seems to work perfectly with L5.

**Comment by adamwathan** [comment]
I haven't tested it with Laravel 5 yet but I would be really surprised if it didn't already work :) The only thing I'll really have to look into is if any CSRF token related things changed that I'll have to update in the service provider.

Going to test this afternoon and push out any changes necessary.

**Comment by adamwathan** [comment]
Double checked, all works great, no changes necessary :) Updated the docs a bit to reflect that.

**Comment by sdebacker** [comment]
I've found a bug: with input that have brackets in its name, errors are not shown. Not sure if it's laravel 5 only. I made a PR in adamwathan/form repository.
