### ISSUE TITLE
.form-group customization?

### ISSUE THREAD

**Issue by JerseyMilker** [adamwathan/bootforms#48]
I often layout my forms using Bootstrap's grid system, ie) http://puu.sh/gsISV/575bc100fb.png

What do you think of adding the following two methods?
```
BootForm::text('Name', 'name')->groupAttribute('class', 'form-group col-md-6')
BootForm::text('Name', 'name')->groupAddClass('col-md-6')
```

Either of the above would output...
```
<div class="form-group col-md-6">
  ...
</div>
```

You can see I am mirroring the attribute() and addClass() methods you already have implemented, but for .form-group elements instead of .form-control elements.  I feel this would add more layout flexibility.  Thoughts?

PS. Input groups would also be sick for those icons I have in there.  I see there's another issue open for that though ;)

**Comment by JerseyMilker** [comment]
Though I suppose this is not a big issue, since I can wrap with HTML for grid layouts.
```
<div class="col-md-6">
	{!! BootForm::text('Name:', 'name') !!}
</div>
```
Feel free to close this issue if you find my suggestion unnecessary.

**Comment by JerseyMilker** [comment]
Though I suppose this is not a big issue, since I can wrap with HTML for grid layouts.
```
<div class="col-md-6">
	{!! BootForm::text('Name:', 'name') !!}
</div>
```
I still think the option would be nice, but feel free to close this issue if you find my suggestion unnecessary.

**Comment by adamwathan** [comment]
Yeah I was going to suggest just doing it that way. There's so many customizations I *could* do but I don't know if it ends up being worth it. I think once you want something remotely custom it's just better to write the markup. This package is really helpful for prototyping and stuff but that's the only real goal.

**Comment by JerseyMilker** [comment]
Fair enough :)

Also unrelated, but could I ask your advice?  How would you go about showing which fields are required before user has submitted the form?

**Comment by adamwathan** [comment]
Honestly usually just something in the label, or if you want to get clever you can use the HTML5 required attribute and add an asterisk or something with [CSS pseudo elements](https://css-tricks.com/almanac/selectors/r/required/).

```
BootForm::text('First Name', 'first_name')->required();
```

**Comment by JerseyMilker** [comment]
Cool thanks, I'll check it out.  Anyway, thanks for BootForm... Very slick.
