### ISSUE TITLE
Optional label

### ISSUE THREAD

**Issue by arall** [adamwathan/bootforms#52]
There is any way to create form elements without label?

Something like this will be usefull:

```php
{!! BootForm::text(null, 'email')->placeholder('Email') !!}
``` 

```html
<input class="form-control" placeholder="E-mail" name="email" type="email">
```

**Comment by adamwathan** [comment]
Yup you can do this like so:

`{!! BootForm::text('Email', 'email')->placeholder('Email')->hideLabel() !!}`

This will add Bootstrap's `sr-only` class to your label, so your labels will still be there for accessibility reasons on screenreaders, but not visible in the browser.

**Comment by arall** [comment]
Oh, nice! Thanks.
