### ISSUE TITLE
Multiple Select

### ISSUE THREAD

**Issue by shijupoothotta** [adamwathan/bootforms#55]
How can I implement a multiple select box?
'<$select multiple$>

**Comment by adamwathan** [comment]
Hey man, try BootForm::select($label, $name, $options)->multiple("multiple");

**Comment by shijupoothotta** [comment]
Not checked 
BootForm::select($label, $name, $options)->multiple("multiple");
But this works:
BootForm::select($label, $name, $options)->attribute("multiple","multiple");

**Comment by xanhast** [comment]
This will display a multiple select input, however the request only contains 1 selection?
