### ISSUE TITLE
Binding to model

### ISSUE THREAD

**Issue by blonkm** [adamwathan/bootforms#58]
I don't know if this is at all possible, but I don't see an example of binding to a model. How do I do that?

**Comment by adamwathan** [comment]
Hey man, yeah totally possible! It's documented here:

https://github.com/adamwathan/form/blob/master/readme.md#model-binding

Apparently I still don't do a good enough job pointing people to those docs in the read me :( really don't want to completely duplicate all the docs but maybe need to at this point.

**Comment by blonkm** [comment]
Also, sorry to continue on this: how would I make a form for an edit route. What I have now is:
{{ Form::model($club, array('method' => 'PATCH', 'route' => array('clubs.update', $club->id))) }}

So how would that work in this package?

**Comment by adamwathan** [comment]
You'd want something like this (might not be _exact_ just winging it):

```
{!! BootForm::open()->action(route('clubs.update', ['id' => $club->id])) !!}
{!! BootForm::hidden('_method', 'PATCH') !!}
{!! BootForm::bind($club) !!}
// form elements here
{!! BootForm::close() !!}
```

I'm going to add a shortcut for patch soon, there are already ones in place for put and delete but missed patch.

It's a framework agnostic package so it doesn't tie tightly into Laravel's URL generation or anything, hence using the `route()` helper provided by Laravel when setting the form action.

**Comment by adamwathan** [comment]
I see you got it in the other issue! :) Hehe..

**Comment by blonkm** [comment]
Oh silly I thought you posted my code LOL
