### ISSUE TITLE
PATCH not implemented

### ISSUE THREAD

**Issue by blonkm** [adamwathan/bootforms#59]
I used this to get PATCH to work

```php
{!! BootForm::openHorizontal(['sm' => [4, 8], 'lg' => [1, 11]])->action(route('clubs.update', [$club->id])) !!}
  {{ BootForm::bind($club) }}
  {!! BootForm::hidden('_method')->value('PATCH') !!}
```

I can see in the code that 'PUT' gets an automatic hidden method, but PATCH doesn't. I am not saying this is a bug, but it's not really elegant to have to put hidden fields myself.

**Comment by adamwathan** [comment]
Totally, feel free to submit a PR (it's a suuuuuper easy addition) if you'd like, or if not I'll try and get it in soon :+1:

**Comment by blonkm** [comment]
I have never submitted a PR, but let me see if I get it right.

**Comment by adamwathan** [comment]
Cool! You'll want to submit to the `adamwathan/form` repo. Here's how it's implemented for PUT and DELETE:

https://github.com/adamwathan/form/blob/master/src/AdamWathan/Form/Elements/FormOpen.php#L52-L60

https://github.com/adamwathan/form/blob/master/tests/FormOpenTest.php#L39-L55

All you'll need to do is add another method to the `FormOpen` class for PATCH, and add a test for it just like the tests for PUT and DELETE that I linked to.

Thanks @blonkm!
