### ISSUE TITLE
Add support to input array

### ISSUE THREAD

**Issue by mjfavaro** [adamwathan/bootforms#64]
I create a request
> php artisan make:request FormRequest

Create a rules for input array
> public function rules()
{
    $rules = [];
    foreach($this->request->get('input_name') as $key)
    {
        $rules['input_name.'.$key] = 'required';
    }
    return $rules;
}

But receive a error:
> FatalErrorException in FormGroup.php line 0: Method AdamWathan\Form\Elements\Text::__toString() must not throw an exception

**Comment by adamwathan** [comment]
Hmm I'm not sure how the FormRequest would be causing this problem, they should be totally unrelated. Can you post a more complete example? Is the project OS?

**Comment by mjfavaro** [comment]
I'm using  
> "laravel/framework": "5.1.*",  
"adamwathan/bootforms": "^0.6.3",  

Imagine this scenario: I need to add a contact list that can grow endlessly

> {!! BootForm::open()->post() !!}
< button id="add-more" type="button" class="btn btn-default">Add More</ button>
                        < div id="elements">
                            {!! BootForm::text('Phone', 'phone[]')->placeholder('Phone') !!}
                        </ div>
                    {!! BootForm::submit('Save')->class('btn btn-primary') !!}
                    {!! BootForm::close() !!}

The button add-more doubles the input form with the name = 'phone []'
> < script>
        $(function() {
            $('#add-more').on('click', function() {
                var element = $($('#elements div.form-group')[0]).html();
                $('#elements').append(element);
            });
        });
    </ script>

Create a request to validate the form
> php artisan make:request ExampleRequest

And change the rules
> public function rules()
    {
        $rules = [];
            foreach($this->request->get('phone') as $index=>$value)
            {
                $rules['phone.'.$index] = 'required';
            }
        return $rules;
        }

Be sure to authorize
> public function authorize()
    {
        return true;
    }

Into controller
> public function postForm(Requests\ExampleRequest $request)
{
dd($request)
}

Load your view and send a empty form.  
IMPORTANT: Use rule "required" cause this error  
> [1/1] FatalErrorException in FormGroup.php line 0: Method AdamWathan\Form\Elements\Text::__toString() must not throw an exception
> [1.]  in FormGroup.php line 0

**Comment by adamwathan** [comment]
Problem is that because your fields are all named `phone[]`, the old values of the `phone[]` key end up coming back as an array instead of a single text value which is throwing off the piece of code that tries to populate the old input since it doesn't know which value to map to which field since they all have the same name.

For now I'd recommend giving each input a unique name with an actual index (eg. `phone[0]`, `phone[1]`, `phone[2]`, etc.)

Sort of sucks but it would be pretty complicated to support otherwise.

**Comment by mjfavaro** [comment]
ok, I'll do it, and congratulations on the package, it is great

**Comment by adamwathan** [comment]
Thanks! If I think of a simple way to make that work I'll definitely get it in there because that's definitely annoying.
