### ISSUE TITLE
Add support for Laravel route

### ISSUE THREAD

**Issue by jrean** [adamwathan/bootforms#65]
Hi @adamwathan,

The package is awesome!
It would be perfect (to me) if I could declare route name (with route parameters) in place for the action.

Is there a reason this is not implemented?
Are you interested by implementing it?

:)

J.

**Comment by jrean** [comment]
Mmm I guess we can use the `route()` helper function inside the action method...
Is that the way he thought the logic?

**Comment by adamwathan** [comment]
Hey man! Yeah I recommend you use the `route()` helper inside of the `action()` method like you're suggesting:

`BootForm::open()->action(route('sweet.website'))`

This package is meant to be framework agnostic so I don't want to couple it tightly to how the routing works in Laravel :+1:

**Comment by jrean** [comment]
Thank you @adamwathan :)
