### ISSUE TITLE
call_user_func_array() expects parameter 1 to be a valid callback, first array member is not a valid class name or object

### ISSUE THREAD

**Issue by canfiax** [adamwathan/bootforms#66]
I am getting the following error:

     call_user_func_array() expects parameter 1 to be a valid callback, first array member is not a valid class name or object

If I am doing:

     {!! BootForm::button('Training done') !!}

Outside of for instance `BootForm::openHorizontal`

I would expect the library to work outside as well

**Comment by adamwathan** [comment]
The calls need to be within a form that was opened by calling `BootForm::open()` or `BootForm::openHorizontal()` as they render different markup depending on whether it's a stacked form or a horizontal form.

For your situation I would just write the markup, you don't get significant benefit out of using the package for buttons anyways.

`<button class="btn btn-primary">Training done</button>`
