### ISSUE TITLE
input type url support

### ISSUE THREAD

**Issue by flexapp** [adamwathan/bootforms#74]
Hi,
Could you tell me why it does not seem possible to create a input with type = url 
I would like to do :
BootForm::url('My URL', 'my_url');

Thx

**Comment by adamwathan** [comment]
Should be able to do `BootForm::text('My URL', 'my_url')->type('url')`

Will gladly accept a PR for `BootForm::url(...)` though.

**Comment by flexapp** [comment]
Thanks,
I had not thought of this simple solution ;)
