### ISSUE TITLE
possible bug?

### ISSUE THREAD

**Issue by bubach** [adamwathan/bootforms#77]
I'm not sure if I need sleep or if this really is a bug, but in this file you make a call

https://github.com/adamwathan/bootforms/blob/bac19cb71822c7e8bd530b53dccbbf4c9e9b20e4/src/AdamWathan/BootForms/BasicFormBuilder.php#L21

to create a label, with 2 params - and as I can not find any override that call would go all the way down to the element class "Label.php" in the "form" package - which only has one construct param.

Am I correct or did I perhaps miss something?

**Comment by adamwathan** [comment]
You're totally right actually, tests still pass with that parameter removed too. PHP discards extra params so it's harmless, but should totally be removed.

Feel free to PR that change if you'd like the credit! I can push the change up if not :+1: 

Thanks!

**Comment by bubach** [comment]
Feel free to push it yourself, I do not have access to my laptop right now. :)
