### ISSUE TITLE
call user function with hyphen

### ISSUE THREAD

**Issue by lsobral** [adamwathan/bootforms#81]
I used BootForm like below:
`{!! BootForm::text('Dayes', 'days')->size(2)->maxlength(2)->data-inputmask('99')->required() !!}`

Only `data-inputmask` generated error.  I think it's because of the hyphen. What can I do to use?

Thanks

**Comment by adamwathan** [comment]
Hey @lsobral, you should be able to use this syntax in those cases:

{!! BootForm::text('Dayes', 'days')->size(2)->maxlength(2)->data('inputmask', '99')->required() !!}

**Comment by lsobral** [comment]
Thanks. You're very fast! It`s worked.
