### ISSUE TITLE
Displaying errors in Laravel 5.2

### ISSUE THREAD

**Issue by kevosomi** [adamwathan/bootforms#85]
Hello Adamwathan, I love the package and it has saved me days when it comes to forms in the past. However, I recently started working on a new project after the release of Laravel 5.2 and the package is simply not displaying any errors. I am using Requests for validation, as usual, but nothing is being displayed as the error despite redirecting back to the form and with all fields being unset. Please help.

**Comment by adamwathan** [comment]
Make sure your routes are defined in the new `web` group. Any routes defined outside of there do not have sessions enabled by default. Betting that is the issue!

**Comment by adamwathan** [comment]
Here's a working example project to compare against if that's not the problem: https://github.com/adamwathan/bootforms-52-example

**Comment by kevosomi** [comment]
It worked! Thank you.
