### ISSUE TITLE
Include Form with Blade

### ISSUE THREAD

**Issue by Iseldore** [adamwathan/bootforms#86]
Hi !

I'm trying to put my form in a form.blade.php and include it in my index.blade.php, but it makes an infinite loop. 

`FatalErrorException in ClassLoader.php line 344:`
`Maximum function nesting level of '100' reached, aborting!`
`[...]`
`at BootFormsServiceProvider->AdamWathan\BootForms\{closure}() in Container.php line 289`

I'm running Laravel 5.2

Thanks !

**Comment by adamwathan** [comment]
Hey @Iseldore! Can you provide something I can reproduce, maybe upload a sample project or at least the contents of your view? It *might* not be a recursion issue, sometimes functions really do get nested that deep and XDebug is a little conservative.

Try sticking this somewhere in your code as a test, the top of the routes file is a decent place to paste it for now:

`ini_set('xdebug.max_nesting_level', 500);`

If that fixes it, it's just XDebug being too conservative. If not, there's some other issue for us to track down!

**Comment by Iseldore** [comment]
`ini_set('xdebug.max_nesting_level', 500);` fixed it. I don't understand why !

You can reproduce with : 

In index.blade.php : 

`@include('form')`

In form.blade.php :

`{!! BootForm::open() !!}`
`{!! BootForm::text('Titre', 'title', null) !!}`
`{!! BootForm::text('Slug', 'slug', null) !!}`
`{!! BootForm::textarea('Contenu', 'content') !!}`
`{!! BootForm::checkbox('Online', 'online')->defaultCheckedState(null) !!}`
`{!! BootForm::submit('Envoyer') !!}`
`{!! BootForm::close() !!}` 

I'll let the `ini_set` for the moment.

Thanks for your rapidity !

**Comment by adamwathan** [comment]
Good to hear! So there's no bug or anything, just more nested function calls happening than XDebug thinks is normal. This happens in Laravel applications pretty often honestly!

Your best bet is to change your actual PHP INI settings for XDebug and raise that max nesting level there so you can remove it from your code.

If you're using Homestead, you can make that change here:

`/etc/php5/fpm/conf.d/20-xdebug.ini`

Then just restart PHP FPM, which is likely one of these two commands:

`sudo service php-fpm restart` or `sudo service php5-fpm restart`

**Comment by Iseldore** [comment]
Very good ! Thank you so much
