### ISSUE TITLE
BootForm and Laravel 5.2 code issue

### ISSUE THREAD

**Issue by petyots** [adamwathan/bootforms#89]
Hello, when using laravel 5.2 with BootForm you can use php artisan because it throws this exception : 

```

[Symfony\Component\Debug\Exception\FatalThrowableError]                      
  Fatal error: Call to undefined method Illuminate\Foundation\Application::bi  
  ndShared() 

```

I found this after quick search  https://github.com/laracasts/flash/pull/53 . I opened /BootForms/BootForm.php and i found that 

```
<?php namespace AdamWathan\BootForms;

use Illuminate\Html\FormBuilder;

```
lluminate\Html\ is undefined class. I don't have time right now to check all the files, so can you @adamwathan please tell me exactly which files i have to update so i can fix it. Thank in advance.

**Comment by petyots** [comment]
I made mistake the problem is not in your package sorry.

**Comment by petyots** [comment]
I made mistake the problem is not in your package sorry.

**Comment by gildniy** [comment]
#https://github.com/laracasts/flash/pull/53
