### ISSUE TITLE
Checkbox not wrapped in form-group

### ISSUE THREAD

**Issue by mtsunu** [adamwathan/bootforms#92]
I tried
`Bootform::chekbox('Groups', 'groups')`

It rendered
`<div class="checkbox">
<label class="control-label"><input type="checkbox" name="groups" value="1" tes="tes">Groups</label>
</div>`

Is this by design? If so, how can I wrap it inside a form-group?

**Comment by adamwathan** [comment]
Yeah it generates the markup recommended by the Bootstrap docs: http://getbootstrap.com/css/#default-stacked

If you wrapped every checkbox in a form group, they would be very spaced out, whereas normally you need a group of checkboxes near each other.

To wrap it in a form group, just wrap it in a form group :)

```
<div class="form-group">
    {!! BootForm::checkbox('Groups', 'groups') !!}
</div>
```
