### ISSUE TITLE
Select its not  preserving the old input

### ISSUE THREAD

**Issue by juanitodelcielo** [adamwathan/bootforms#96]
Fail
{!! BootForm::select('Máquinas', 'machines[]')->options($machines)->class('form-control js-select2')->multiple()->select($reference->machines) !!}

Success
{{ Form::select('operations[]', $operations, $machine->operations, ['multiple' => 'multiple', 'class' => 'form-control js-select2']) }}

**Comment by adamwathan** [comment]
The problem is you are using the `select` method which does a force select, ignoring any old input or model binding.

Use `defaultValue` instead:

```
{!! BootForm::select('Máquinas', 'machines[]')->options($machines)->class('form-control js-select2')->multiple()->defaultValue($reference->machines) !!}
```
