### ISSUE TITLE
Inputs widths

### ISSUE THREAD

**Issue by lsobral** [adamwathan/bootforms#98]
Is it possible to define widths to inputs or selects using bootstrap classes. 
All inputs occupy the whole line and a field for phone could be less.
Thanks

**Comment by adamwathan** [comment]
Hey Luiz! You can add any classes you like using the `->addClass()` method. I don't *think* Bootstrap provides width classes out of the box that you could apply to a form element, but you could define a few of your own helper classes, like this sort of thing:

```
// These widths are just made up, of course you'd have to figure out something that works for your app
.form-control-short { max-width: 10em; }
.form-control-medium { max-width: 15em; }
```

...and then add them to your BootForms elements like this:

```
{!! BootForm::text('Phone', 'phone')->addClass('form-control-short') !!}
```

**Comment by lsobral** [comment]
Thanks. I'm going to do this.
